edition = "2021"
comment_width = 120
max_width = 120
chain_width = 120
attr_fn_like_width = 120
fn_call_width = 120
function_arguments = "Visual"
brace_style = "PreferSameLine"
use_field_init_shorthand = true
reorder_impl_items = true
imports_granularity = "module"
group_imports = "StdExternalCrate"
