[package]
name = "dmodman"
version = "0.1.0"
authors = ["dandels <dandels.sh@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "1.0"
reqwest = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "1.7.0"
