## dmodman example config

## Modding profile.
## You should set this to something different for each game or mod loadout.
## It appends a subdirectory to download_dir and install_dir.
## Default: none
#profile = "morrowind"

## Download directory. Default: $XDG_DOWNLOAD_DIR/dmodman
#download_dir = "~/Downloads/dmodman/"

## Directory to extract mods to. Default: $XDG_DATA_HOME/dmodman/
#install_dir = "~/.local/share/dmodman/"
