## dmodman example config
##
## Relative paths like ~/ and environment variables like $HOME are not supported.

## The base download directory as an absolute path.
## Default: $XDG_DOWNLOAD_DIR/dmodman
#download_dir = "/home/user/Downloads/dmodman/"

## If set, appends a subdirectory to the download_dir path.
## For example "morrowind" would set the download dir to $XDG_DOWNLOAD_DIR/dmodman/morrowind.
## Default: none
#profile = "morrowind"
