edition = "2021"
max_width = 120
comment_width = 120
chain_width = 100
attr_fn_like_width = 100
fn_call_width = 100
brace_style = "PreferSameLine"
use_field_init_shorthand = true
reorder_impl_items = true